version: '3.0'

services:
  apache:
    build: .docker/apache
    container_name: pluto_apache
    restart: always
    ports:
      - 4041:80
    volumes:
      - .docker/config/vhosts:/etc/apache2/sites-enabled
      - .:/home/wwwroot/pluto
    depends_on:
      - php
    networks:
      - pluto_network

  php:
    build: .docker/php
    container_name: pluto_php
    volumes:
      - .:/home/wwwroot/pluto
    depends_on:
      - mysql
    networks:
      - pluto_network

  mysql:
    image: mysql
    container_name: pluto_db
    restart: always
    command: "--default-authentication-plugin=mysql_native_password"
    ports:
      - 4042:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: pluto
    networks:
      - pluto_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pluto_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 4043:80
    links:
      - mysql
    networks:
      - pluto_network

networks:
  pluto_network:
